services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment: 
      POSTGRES_USER: social_user
      POSTGRES_PASSWORD: social_pass
      POSTGRES_DB: social_platform
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: